version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/StreamNest
      SPRING_DATASOURCE_USERNAME: user_login
      SPRING_DATASOURCE_PASSWORD: user_password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_REGION: eu-central-1
      AWS_S3_ACCESS_KEY: admin
      AWS_S3_SECRET_KEY: admin123
      AWS_S3_BUCKET: streamnest-bucket
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ##############
      SPRING_MAIL_PASSWORD: ################
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10TB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10TB
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
      - minio
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: StreamNest
      POSTGRES_USER: user_login
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
